### ISSUE TITLE
Laser and Spot issues

### ISSUE THREAD

**Issue by Yablo49** [SBDPlugins/ShowControl#23]
Hi, I want to know how we can use spot and laser system because when I try, lasers are fix and spot doesn't apperead.
Thanks in advance !
![Capture d'écran 2023-10-31 143214](https://github.com/SBDPlugins/ShowControl/assets/90402442/0449eab3-dd6e-499e-89c7-995430c538a5)

**Comment by stijnb1234** [comment]
Known, working on it.

**Comment by stijnb1234** [comment]
Not sure, when I have time to look into it.

**Comment by Yablo49** [comment]
No problem, thank you and have a nice day!

**Comment by stijnb1234** [comment]
Fixed in v1.5, please note Spots do not work until this issue is resolved: https://github.com/SkytAsul/GuardianBeam/issues/21
