### ISSUE TITLE
Spot Kick problem

### ISSUE THREAD

**Issue by Yablo49** [SBDPlugins/ShowControl#25]
Hi,
I've a bugged spot and laser on my server and when I'm near of them I'm kicked. How can I remove them ?
Thanks !

**Comment by stijnb1234** [comment]
Known problem with the spots. As mentioned in the plugin description they can't be used yet. Will update when resolved.

**Comment by Yablo49** [comment]
Yes I know but here is a command to delete spots and laser ?
Because I can't remove them so I'm always kicked !
Thanks !

**Comment by stijnb1234** [comment]
You can remove the cue from the show's yml file in the plugin folder.

10 nov. 2023 20:29:22 Yablo49 ***@***.***>:

**Comment by stijnb1234** [comment]
Resolved
